Environment_4 As CommandComponent:
    AutoSave: =true
    DataSource: ='Access Profiles'
    Fill: =RGBA(0, 0, 0, 0)
    Height: =0
    Icon: =SampleImage
    OnSelect: =true
    Selected: |-
        ={ Item: {}, AllItems:[], Unsaved: false, State: SelectedState.Edit }
    SelectionMax: =100
    SelectionMin: =100
    Title: = 
    Tooltip: = 
    Visible: =Self.Selected.Item.'Status Reason' = 'Status Reason (Access Profiles)'.Active
    Width: =0
    X: =0
    Y: =0
    ZIndex: =1

