// <copyright file="PreOperationcat_accessrequestCreate.cs" company="">
// Copyright (c) 2023 All Rights Reserved
// </copyright>
// <author></author>
// <date>5/27/2023 5:46:11 PM</date>
// <summary>Implements the PreOperationcat_accessrequestCreate Plugin.</summary>
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>

using System;
using System.Security.Principal;
using System.ServiceModel;
using Microsoft.Xrm.Sdk;

namespace AccessManagementPlugins.CreateAccessRequest
{

    /// <summary>
    /// PreOperationcat_accessrequestCreate Plugin.
    /// </summary>    
    public class PreOperationcat_accessrequestCreate: PluginBase
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PreOperationcat_accessrequestCreate"/> class.
        /// </summary>
        /// <param name="unsecure">Contains public (unsecured) configuration information.</param>
        /// <param name="secure">Contains non-public (secured) configuration information.</param>
        public PreOperationcat_accessrequestCreate(string unsecure, string secure)
            : base(typeof(PreOperationcat_accessrequestCreate))
        {
            
           // TODO: Implement your custom configuration handling.
        }


        /// <summary>
        /// Main entry point for he business logic that the plug-in is to execute.
        /// </summary>
        /// <param name="localContext">The <see cref="LocalPluginContext"/> which contains the
        /// <see cref="IPluginExecutionContext"/>,
        /// <see cref="IOrganizationService"/>
        /// and <see cref="ITracingService"/>
        /// </param>
        /// <remarks>
        /// </remarks>
        protected override void ExecuteCdsPlugin(ILocalPluginContext localContext)
        {
            if (localContext == null)
            {
                throw new InvalidPluginExecutionException(nameof(localContext));
            }           
            // Obtain the tracing service
            ITracingService tracingService = localContext.TracingService;

            try
            { 
                // Obtain the execution context from the service provider.  
                IPluginExecutionContext context = (IPluginExecutionContext)localContext.PluginExecutionContext;

                // Obtain the organization service reference for web service calls.  
                IOrganizationService currentUserService = localContext.CurrentUserService;

                Entity accessRequest = (Entity)context.InputParameters["Target"];

                // Set Status Reason to "Request" (1)
                accessRequest.Attributes["statuscode"] = 1;

                context.InputParameters["Target"] = accessRequest;

            }	
            // Only throw an InvalidPluginExecutionException. Please Refer https://go.microsoft.com/fwlink/?linkid=2153829.
            catch (Exception ex)
            {
                tracingService?.Trace("An error occurred executing Plugin AccessManagementPlugins.CreateAccessRequest.PreOperationcat_accessrequestCreate : {0}", ex.ToString());
                throw new InvalidPluginExecutionException("An error occurred executing Plugin AccessManagementPlugins.CreateAccessRequest.PreOperationcat_accessrequestCreate .", ex);
            }	
        }
    }
}
